services:
  pg_database:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "/workspaces/DE_Zoomcamp_module_1_docker_learning/ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=deepa.arjunan@outlook.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"